require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/concepts/**/*'

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/*'

# RSpec cops
RSpec/NestedGroups:
  Max: 4

RSpec/MultipleExpectations:
  Enabled: false
