version: '3.2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: './entrypoint.sh'
    command: bundle exec puma -C config/puma.rb
    tty: true
    stdin_open: true
    env_file: docker.env
    container_name: video_trim_app
    volumes:
      - './app:/var/www/video_trim/app'
      - './db:/var/www/video_trim/db'
      - './config:/var/www/video_trim/config'
      - './lib:/var/www/video_trim/lib'
      - './spec:/var/www/video_trim/spec'
      - './Gemfile:/var/www/video_trim/Gemfile'
      - './Gemfile.lock:/var/www/video_trim/Gemfile.lock'
      - 'uploads:/var/www/video_trim/public/uploads'
    ports:
      - '3000:3000'
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
  mongo:
    image: 'mongo:3.6-xenial'
    env_file: docker.env
    container_name: video_trim_mongo
    volumes:
      - 'mongodata:/var/lib/mongo/data'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet 1
  redis:
    image: 'redis:4.0.13-alpine'
    container_name: video_trim_redis
    volumes:
      - 'redisdata:/var/lib/redis/data'
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "localhost", "ping"]
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq -C config/sidekiq.yml
    env_file: docker.env
    container_name: video_trim_sidekiq
    volumes:
      - type: volume
        source: uploads
        target: /var/www/video_trim/public/uploads
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: ["CMD-SHELL", "ps ax | grep -v grep | grep sidekiq || exit 1"]

volumes:
  mongodata:
    external: false
  uploads:
    external: false
  redisdata:
    external: false
